### ISSUE TITLE
Mod Compatibility

### ISSUE THREAD

**Issue by TheMagicalSquid** [Zaggy1024/LC_NutcrackerFixes#1]
Does this mod work with this? https://thunderstore.io/c/lethal-company/p/Hexi/HexiBetterShotgun/

**Comment by Zaggy1024** [comment]
I haven't tested it, but I believe it should. That mod only really replaces the shooting function, which means that the patches to the vanilla hit registration will just be replaced with their implementation instead. All the rest of the patches included in NutcrackerFixes should function as normal.

The only situation I can see where this wouldn't work is if you see errors pop up in the console related to either mod when starting up or when shooting the shotgun.
